# Generated by Django 4.2.7 on 2023-11-28 20:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='id_responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.responsible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debts',
            name='month',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
    ]
