# Generated by Django 4.2.7 on 2023-11-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_debts_id_responsible_debts_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cpnj', models.CharField(max_length=14)),
                ('digital_bank', models.BooleanField()),
            ],
        ),
    ]
