# Generated by Django 4.2.7 on 2023-11-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='cpnj',
        ),
        migrations.AddField(
            model_name='bank',
            name='cnpj',
            field=models.CharField(default='', max_length=18),
        ),
    ]
