# Generated by Django 4.2.7 on 2023-11-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_remove_bank_cpnj_bank_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debts',
            name='bank',
        ),
        migrations.AddField(
            model_name='debts',
            name='id_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.bank'),
        ),
    ]
