# Generated by Django 4.2.7 on 2023-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_debts_id_alter_debts_id_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
