# Generated by Django 4.2.7 on 2024-06-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_debts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='cnpj',
        ),
    ]
